### ISSUE TITLE
How long does the program take to run

### ISSUE THREAD

**Issue by lilyhhha** [Joy-Xue/DDRM#1]
Hello, after running DDRM/main.m for two hours, still only 
“Starting parallel pool (parpool) using the 'local' profile... Connected to the parallel pool (number of workers: 2). ”
No result image is displayed, may I ask how long it will take for this program to run and produce the result, or what needs to be changed in my matlab configuration?

**Comment by Joy-Xue** [comment]
I downloaded the code and tested it on a desktop with 128G RAM and 8 cores. In the default setting (i.e., T = 32, stock dataset), the running time is 2810 seconds (almost 50 mins). I also tested the code on a desktop with 32G RAM and 6 cores. When T = 16, the running time is 173 seconds and 276 seconds for synthetic and stock datasets respectively. 

“Starting parallel pool (parpool) using the 'local' profile... Connected to the parallel pool (number of workers: 2). ” This warning appeared just because "parfor" command is used, and it means that your computer has two cores.  Running the code in the default setting usually needs lots of time. For simplicity, I suggest you can test the code in a simple setting (e.g., on the syn dataset and T=16).

**Comment by Joy-Xue** [comment]
> Hello, after running DDRM/main.m for two hours, still only “Starting parallel pool (parpool) using the 'local' profile... Connected to the parallel pool (number of workers: 2). ” No result image is displayed, may I ask how long it will take for this program to run and produce the result, or what needs to be changed in my matlab configuration?

I downloaded the code and tested it on a desktop with 128G RAM and 8 cores. In the default setting (i.e., T = 32, stock dataset), the running time is 2810 seconds (almost 50 mins). I also tested the code on a desktop with 32G RAM and 6 cores. When T = 16, the running time is 173 seconds and 276 seconds for synthetic and stock datasets respectively.

“Starting parallel pool (parpool) using the 'local' profile... Connected to the parallel pool (number of workers: 2). ” This warning appeared just because "parfor" command is used, and it means that your computer has two cores. Running the code in the default setting usually needs lots of time. For simplicity, I suggest you can test the code in a simple setting (e.g., on the syn dataset and T=16).

**Comment by Joy-Xue** [comment]
> Hello, after running DDRM/main.m for two hours, still only “Starting parallel pool (parpool) using the 'local' profile... Connected to the parallel pool (number of workers: 2). ” No result image is displayed, may I ask how long it will take for this program to run and produce the result, or what needs to be changed in my matlab configuration?

Also, the code cannot generate a figure. Figures are needed to be plotted by the running results. I have uploaded a file on plotting figures for your reference.

**Comment by lilyhhha** [comment]
Thank you for your reply.
